export enum CommandEnum {
  FocusSearchInput = 'FocusSearchInput',
  OpenMainWindow = 'OpenMainWindow',
  QuitMainWindow = 'QuitMainWindow',
  CloseMainWindow = 'CloseMainWindow',
  MinimizeMainWindow = 'MinimizeMainWindow',
  MaximizeMainWindow = 'MaximizeMainWindow',
  OpenAppsNavDialog = 'OpenAppsNavDialog',
  OpenSettingsDialog = 'OpenSettingsDialog',
  OpenCardAddDialog = 'OpenCardAddDialog',
  OpenPasswordGeneratorDialog = 'OpenPasswordGeneratorDialog',
  OpenPasswordSetDialog = 'OpenPasswordSetDialog',
  OpenDeletedCardsDialog = 'OpenDeletedCardsDialog',
  OpenHistoryDialog = 'OpenHistoryDialog',
  OpenImportDialog = 'OpenImportDialog',
  OpenExportDialog = 'OpenExportDialog',
  OpenHelpDialog = 'OpenHelpDialog',
  OpenTutorialDialog = 'OpenTutorialDialog',
}
